# https://clientworker.js.org/
name: ClientWorker 
cleaninterval: 1000*30 # 每30秒检测并清理一次缓存
# ClientWorker热补丁
hotpatch:
  - https://jsd.cxl2020mc.top/npm/clientworker@latest
  - https://cdn3.tianli0.top/npm/clientworker@latest
  - https://project.cnortles.top/proxy/jsdelivr/npm/clientworker@latest
  - https://raw.githubusercontent.com/ChenYFan/ClientWorker/gh-pages/cw.js
  - https://cdn.jsdelivr.net/gh/ChenYFan/ClientWorker/cw.js
# Config热更新
hotconfig:
  - https://cdn.vercel.blog.cxl2020mc.top/config.yaml
  - https://cfpage.blog.cxl2020mc.top/config.yaml
  - https://netlify.blog.cxl2020mc.top/config.yaml
  - https://cdn.blog.cxl2020mc.top/config.yaml
  - https://github.com/cxl2020MC/cxl2020MC.github.io/raw/master/source/config.yaml
  - https://raw.githubusercontent.com/cxl2020MC/cxl2020MC.github.io/master/source/config.yaml
catch_rules:
  # 并发博客
  # - rule: _
  #   transform_rules:
  #     - search: _
  #       replace:
  #         - www.cxl2020mc.top
  #         # - netlify.blog.cxl2020mc.top #会带来cors问题
  #         - cfpage.blog.cxl2020mc.top # cfpage
  #         - cdn.vercel.blog.cxl2020mc.top # cyf vercel自选节点
  #         - cdn.blog.cxl2020mc.top # 腾讯云海外加速cdn
  #         - _
  #       action: fetch
  #       fetch:
  #         status: .*
  #         engine: parallel
  #         preflight: false # false
  #         timeout: 30000
  #         delay: 4000 # 为了防止bug
  # npm加速
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm|jsd\.cxl2020mc\.top\/npm|unpkg\.com)
    transform_rules:
      - search: _
        replace:
          - https://jsd.cxl2020mc.top/npm
          - https://vercel.jsd.cxl2020mc.top/npm
          - https://jsdcxl2020mc.domain.qystu.cc/npm
          - https://unpkg.cnortles.top
          - https://cdn.cnortles.top/npm
          - https://project.cnortles.top/proxy/jsdelivr/npm
          - https://jsdelivr.pai233.top/npm
          - https://cdn.jsdelivr.net/npm
          - https://cdn3.tianli0.top/npm
          - https://jsd.cky.codes/npm
          - https://unpkg.com
          - _
        action: fetch
        fetch:
          # 304状态码，表示自上次访问以来，请求的资源未被修改。该状态码较少出现，所以基本没啥用(大文件除外)
          status: 200|3.*
          engine: parallel
          preflight: false # false
          timeout: 30000
          cache:
            expire: 1000*60*60*8 # 缓存8小时
            delay: 300
  # github加速
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/gh|jsd\.cxl2020mc\.top\/gh)
    transform_rules:
      - search: _
        replace:
          - https://jsd.cxl2020mc.top/gh
          - https://vercel.jsd.cxl2020mc.top/gh
          - https://jsdcxl2020mc.domain.qystu.cc/gh
          - https://cdn.cnortles.top/gh
          - https://project.cnortles.top/proxy/jsdelivr/gh
          - https://jsdelivr.pai233.top/gh
          - https://cdn.jsdelivr.net/gh
          - https://cdn3.tianli0.top/gh
          - https://jsd.cky.codes/gh
          - _
        action: fetch
        fetch:
          status: 200|3.*
          engine: parallel
          preflight: false # false
          timeout: 30000
          cache:
            expire: 1000*60*60*8 # 缓存8小时
            delay: 300
  - rule: ^https\:\/\/cxl2020mc-1304820025\.file\.myqcloud\.com
    transform_rules:
      - search: _
        action: fetch
        fetch:
          status: .*
          engine: fetch
          preflight: true # false
          timeout: 50000
          cache:
            expire: 1000*60*5 # 缓存5分钟
            delay: 300
  # api图片缓存
  - rule: ^https\:\/\/api\.cxl2020mc\.top
    transform_rules:
      - search: _
        action: fetch
        fetch:
          status: .*
          engine: fetch
          preflight: true # false
          timeout: 50000
          cache:
            expire: 1000*60*60 # 缓存60分钟
            delay: 300
  # 第三方api图片缓存
  - rule: ^https\:\/\/api\.dujin\.org
    transform_rules:
      - search: _
        action: fetch
        fetch:
          status: .*
          engine: fetch
          preflight: true # false
          timeout: 50000
          cache:
            expire: 1000*60*60*8 # 缓存8小时
            delay: 300
- rule: busuanzi\.ibruce\.info\/busuanzi\/.*\/busuanzi.pure.mini.js
    transform_rules:
      - search: _
        replace: jsd.cxl2020mc.top/npm/penndu@1.0.0/bsz.js
        action: fetch
        fetch:
          status: .*
          engine: fetch
          preflight: true # false
          timeout: 50000
          cache:
            expire: 1000*60*60 # 缓存60分钟
            delay: 300
  # 不劫持（丢给浏览器）
  - rule: .*
    transform_rules:
      - search: _
        action: skip #? 2.8.1新增，跳过cw规则（ 现在已经不在需要，但为了兼容性和避免未知bug建议留下此配置）